# @package _global_

defaults:
  - _self_
  - data: mnist.yaml
  - model: mnist.yaml
  - callbacks: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: null
  - hparams_search: null
  - optional local: default.yaml
  - debug: null

task_name: "train"
tags: ["dev"]
train: True
test: True
compile: False
ckpt_path: null
seed: null
